# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'Server', '\u670d\u52a1\u5668'), (b'Switch', '\u4ea4\u6362\u673a'), (b'Router', '\u8def\u7531\u5668'), (b'Firewall', '\u9632\u706b\u5899')], default=b'Server', max_length=16, null=True, verbose_name='\u7c7b\u522b')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('intranet', models.GenericIPAddressField(verbose_name='\u5185\u7f51IP')),
                ('internet', models.GenericIPAddressField(null=True, verbose_name='\u516c\u7f51IP')),
                ('status', models.CharField(blank=True, choices=[(b'In use', '\u5f00\u542f'), (b'Out of use', '\u5173\u95ed')], default=b'In use', max_length=12, null=True, verbose_name='\u72b6\u6001')),
                ('cabinet_num', models.CharField(max_length=128, verbose_name='\u673a\u67dc\u7f16\u53f7')),
                ('cabinet_order', models.CharField(max_length=128, verbose_name='\u673a\u67dc\u4e2d\u7684\u5e8f\u53f7')),
                ('vendor', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4f9b\u5e94\u5546')),
                ('model', models.CharField(blank=True, max_length=54, null=True, verbose_name='\u578b\u53f7')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u7801')),
                ('comment', models.TextField(blank=True, default=b'', max_length=128, verbose_name='\u5907\u6ce8')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.IntegerField(null=True, verbose_name='CPU\u4e2a\u6570')),
                ('cpu_cores', models.IntegerField(null=True, verbose_name='CPU\u6838\u5fc3\u6570')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u786c\u76d8')),
                ('platform', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e73\u53f0')),
                ('os', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7cfb\u7edf')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u521b\u5efa\u4eba')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ENV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('contact', models.CharField(blank=True, max_length=128, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u5730\u5740')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('created_by', models.CharField(blank=True, max_length=32, verbose_name='Created by')),
                ('comment', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('salt_id', models.CharField(max_length=128, verbose_name='SaltID')),
                ('status', models.CharField(blank=True, choices=[(b'In use', '\u5f00\u542f'), (b'Out of use', '\u5173\u95ed')], default=b'In use', max_length=12, null=True, verbose_name='\u72b6\u6001')),
                ('env', models.CharField(blank=True, choices=[(b'Dev', '\u5f00\u53d1\u73af\u5883'), (b'UAT', 'UAT\u73af\u5883'), (b'Prod', '\u751f\u4ea7\u73af\u5883')], default=b'Dev', max_length=12, null=True, verbose_name='\u8fd0\u884c\u73af\u5883')),
                ('intranet', models.GenericIPAddressField(verbose_name='\u5185\u7f51IP')),
                ('internet', models.GenericIPAddressField(null=True, verbose_name='\u516c\u7f51IP')),
                ('cpu_cores', models.IntegerField(null=True, verbose_name='CPU cores')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='Memory')),
                ('disk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Disk info')),
                ('platform', models.CharField(blank=True, max_length=128, null=True, verbose_name='Platform')),
                ('os', models.CharField(blank=True, max_length=128, null=True, verbose_name='OS')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='OS version')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default=b'', max_length=128, verbose_name='\u5907\u6ce8')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='assets.Asset', verbose_name='\u6240\u5c5e\u4e3b\u673a')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.IDC', verbose_name='IDC'),
        ),
    ]
