# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='cabinet_number',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='cabinet_orde',
        ),
        migrations.AddField(
            model_name='asset',
            name='cabinet_num',
            field=models.CharField(default=0, max_length=128, unique=True, verbose_name='cabinet_num'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='cabinet_order',
            field=models.CharField(default=0, max_length=128, unique=True, verbose_name='cabinet_order'),
            preserve_default=False,
        ),
    ]
