# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20171206_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.ENV', verbose_name='ENV'),
        ),
    ]
