# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20171206_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.ENV', verbose_name='ENV'),
        ),
    ]
