# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20171206_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('hostname', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Hostname')),
                ('env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.ENV', verbose_name='ENV')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.Asset')),
            ],
        ),
        migrations.RenameField(
            model_name='info',
            old_name='disk_info',
            new_name='disk',
        ),
        migrations.RemoveField(
            model_name='info',
            name='disk_total',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hostname_raw',
        ),
        migrations.RemoveField(
            model_name='info',
            name='os_arch',
        ),
        migrations.AddField(
            model_name='server',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='assets.Info'),
        ),
    ]
