# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20171207_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, choices=[(b'In use', '\u5f00\u542f'), (b'Out of use', '\u5173\u95ed')], default=b'In use', max_length=12, null=True, verbose_name='Asset status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Server', '\u670d\u52a1\u5668'), (b'Switch', '\u4ea4\u6362\u673a'), (b'Router', '\u8def\u7531\u5668'), (b'Firewall', '\u9632\u706b\u5899')], default=b'Server', max_length=16, null=True, verbose_name='\u7c7b\u522b'),
        ),
    ]
