# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20171207_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cabinet_num',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u673a\u67dc\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cabinet_order',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u673a\u67dc\u4e2d\u7684\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True, default=b'', max_length=128, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_cores',
            field=models.IntegerField(null=True, verbose_name='CPU\u6838\u5fc3\u6570'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_count',
            field=models.IntegerField(null=True, verbose_name='CPU\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u786c\u76d8'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='internet',
            field=models.GenericIPAddressField(db_index=True, verbose_name='\u516c\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='intranet',
            field=models.GenericIPAddressField(db_index=True, verbose_name='\u5185\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=54, null=True, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e73\u53f0'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, choices=[(b'In use', '\u5f00\u542f'), (b'Out of use', '\u5173\u95ed')], default=b'In use', max_length=12, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4f9b\u5e94\u5546'),
        ),
    ]
