# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20171207_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cabinet_num',
            field=models.CharField(max_length=128, verbose_name='\u673a\u67dc\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cabinet_order',
            field=models.CharField(max_length=128, verbose_name='\u673a\u67dc\u4e2d\u7684\u5e8f\u53f7'),
        ),
    ]
