# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20171207_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='internet',
            field=models.GenericIPAddressField(verbose_name='\u516c\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='intranet',
            field=models.GenericIPAddressField(verbose_name='\u5185\u7f51IP'),
        ),
    ]
