# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20171207_0709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ip',
        ),
        migrations.AddField(
            model_name='server',
            name='internet',
            field=models.GenericIPAddressField(default=0, verbose_name='\u516c\u7f51IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='intranet',
            field=models.GenericIPAddressField(default=0, verbose_name='\u5185\u7f51IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(blank=True, choices=[(b'In use', '\u5f00\u542f'), (b'Out of use', '\u5173\u95ed')], default=b'In use', max_length=12, null=True, verbose_name='\u72b6\u6001'),
        ),
    ]
