# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=128, verbose_name='Job_id')),
                ('func', models.CharField(max_length=128, verbose_name='\u65b9\u6cd5')),
                ('target', models.CharField(max_length=128, verbose_name='\u76ee\u6807\u673a\u5668')),
                ('args', models.CharField(max_length=128, verbose_name='\u53c2\u6570')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('create_by', models.CharField(max_length=128, verbose_name='\u521b\u5efa\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_id', models.CharField(max_length=128, verbose_name='Job_id')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('ret_code', models.IntegerField()),
                ('result', models.TextField(blank=True, null=True, verbose_name='\u8fd4\u56de\u7ed3\u679c')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.Job')),
            ],
        ),
    ]
