# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
