# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20171212_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5b8c\u6210'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6210\u529f'),
        ),
    ]
